In [1]:
import pandas as pd
import numpy as np


In [2]:
# Fixando a semente inicial
# https://stackoverflow.com/questions/54432394/keras-getting-different-results-with-set-seed
# Seed value (can actually be different for each attribution step)
seed_value= 0

# 1. Set `PYTHONHASHSEED` environment variable at a fixed value
import os
os.environ['PYTHONHASHSEED']=str(seed_value)

# 2. Set `python` built-in pseudo-random generator at a fixed value
import random
random.seed(seed_value)

# 3. Set `numpy` pseudo-random generator at a fixed value
import numpy as np
np.random.seed(seed_value)


In [3]:
# tensorflow
#tf.set_random_seed=seed_value

Cria cabeçalho para 50 colunas

In [4]:
total_colunas=50
colunas = list(range(0,total_colunas))
cabecalho=' '.join(str(e) for e in colunas)

Le arquivo sem o cabeçalho

In [5]:
with open('Thunderbird_1000_total.log') as fp:
    arquivo_log = fp.read()

Junta os dois arquivos

In [6]:
dados = cabecalho
dados += "\n"
dados += arquivo_log

In [7]:
with open('Arq_trabalho', 'w') as fp:
  fp.write(dados)

In [8]:
registros = pd.read_csv('Arq_trabalho', sep=' ', usecols=list(range(0,total_colunas)))
registros

0           1           2      3    4   5  ...  44  45  46  47  48  49
0     1  1131685687  2005.11.10  bn257  Nov  10  ... NaN NaN NaN NaN NaN NaN
1     1  1131685687  2005.11.10  bn257  Nov  10  ... NaN NaN NaN NaN NaN NaN
2     1  1131685688  2005.11.10  bn257  Nov  10  ... NaN NaN NaN NaN NaN NaN
3     1  1131685688  2005.11.10  bn257  Nov  10  ... NaN NaN NaN NaN NaN NaN
4     1  1131685688  2005.11.10  bn257  Nov  10  ... NaN NaN NaN NaN NaN NaN
...  ..         ...         ...    ...  ...  ..  ...  ..  ..  ..  ..  ..  ..
2008  0  1131563675  2005.11.09  cn450  Nov   9  ... NaN NaN NaN NaN NaN NaN
2009  0  1131563675  2005.11.09  cn450  Nov   9  ... NaN NaN NaN NaN NaN NaN
2010  0  1131563675  2005.11.09  cn450  Nov   9  ... NaN NaN NaN NaN NaN NaN
2011  0  1131563675  2005.11.09  cn450  Nov   9  ... NaN NaN NaN NaN NaN NaN
2012  0  1131563675  2005.11.09  cn450  Nov   9  ... NaN NaN NaN NaN NaN NaN

[2013 rows x 50 columns]

In [9]:
# Retira NaN e passa para string
registros=registros.replace({np.NaN:' '})
registros=registros.astype(str)
registros

0           1           2      3    4   5         6  ... 43 44 45 46 47 48 49
0     1  1131685687  2005.11.10  bn257  Nov  10  21:08:07  ...                     
1     1  1131685687  2005.11.10  bn257  Nov  10  21:08:07  ...                     
2     1  1131685688  2005.11.10  bn257  Nov  10  21:08:08  ...                     
3     1  1131685688  2005.11.10  bn257  Nov  10  21:08:08  ...                     
4     1  1131685688  2005.11.10  bn257  Nov  10  21:08:08  ...                     
...  ..         ...         ...    ...  ...  ..       ...  ... .. .. .. .. .. .. ..
2008  0  1131563675  2005.11.09  cn450  Nov   9  11:14:35  ...                     
2009  0  1131563675  2005.11.09  cn450  Nov   9  11:14:35  ...                     
2010  0  1131563675  2005.11.09  cn450  Nov   9  11:14:35  ...                     
2011  0  1131563675  2005.11.09  cn450  Nov   9  11:14:35  ...                     
2012  0  1131563675  2005.11.09  cn450  Nov   9  11:14:35  ...                     

[2013 rows x 50 columns]

In [10]:
registros['Mensagem completa']=registros.iloc[:, 8:].agg(' '.join, axis=1)
registros.iloc[:,[0,total_colunas]]

0                                  Mensagem completa
0     1  kernel: [KERNEL_IB][tsIbTavorMadProcess][/mnt_...
1     1  kernel: [KERNEL_IB][tsIbTavorMadProcess][/mnt_...
2     1  kernel: [KERNEL_IB][tsIbTavorMadProcess][/mnt_...
3     1  kernel: [KERNEL_IB][tsIbTavorMadProcess][/mnt_...
4     1  kernel: [KERNEL_IB][tsIbTavorMadProcess][/mnt_...
...  ..                                                ...
2008  0  kernel: e1000: eth0: e1000_watchdog: NIC Link ...
2009  0  kernel: e1000: eth1: e1000_probe: Intel(R) PRO...
2010  0  kernel: ehci_hcd 0000:00:1d.7: EHCI Host Contr...
2011  0  kernel: ehci_hcd 0000:00:1d.7: USB 2.0 enabled...
2012  0  kernel: ehci_hcd 0000:00:1d.7: irq 193, pci me...

[2013 rows x 2 columns]

In [11]:
# Existem valores nulos (por coluna)?

print(registros.isnull().any())

0                    False
1                    False
2                    False
3                    False
4                    False
5                    False
6                    False
7                    False
8                    False
9                    False
10                   False
11                   False
12                   False
13                   False
14                   False
15                   False
16                   False
17                   False
18                   False
19                   False
20                   False
21                   False
22                   False
23                   False
24                   False
25                   False
26                   False
27                   False
28                   False
29                   False
30                   False
31                   False
32                   False
33                   False
34                   False
35                   False
36                   False
3

In [12]:
data=pd.DataFrame 
data=registros.iloc[:,[0, total_colunas]]
data.rename(columns={'0':'class','Mensagem completa':'text'}, inplace=True)
data

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4308: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


class                                               text
0        1  kernel: [KERNEL_IB][tsIbTavorMadProcess][/mnt_...
1        1  kernel: [KERNEL_IB][tsIbTavorMadProcess][/mnt_...
2        1  kernel: [KERNEL_IB][tsIbTavorMadProcess][/mnt_...
3        1  kernel: [KERNEL_IB][tsIbTavorMadProcess][/mnt_...
4        1  kernel: [KERNEL_IB][tsIbTavorMadProcess][/mnt_...
...    ...                                                ...
2008     0  kernel: e1000: eth0: e1000_watchdog: NIC Link ...
2009     0  kernel: e1000: eth1: e1000_probe: Intel(R) PRO...
2010     0  kernel: ehci_hcd 0000:00:1d.7: EHCI Host Contr...
2011     0  kernel: ehci_hcd 0000:00:1d.7: USB 2.0 enabled...
2012     0  kernel: ehci_hcd 0000:00:1d.7: irq 193, pci me...

[2013 rows x 2 columns]

Email 21/06/2021 - https://github.com/UKPLab/sentence-transformers

In [13]:
!pip install -U sentence-transformers

     |████████████████████████████████| 92kB 6.5MB/s 
     |████████████████████████████████| 2.5MB 18.3MB/s 
     |████████████████████████████████| 1.2MB 51.8MB/s 
     |████████████████████████████████| 3.3MB 49.6MB/s 
     |████████████████████████████████| 901kB 48.0MB/s 
  Created wheel for sentence-transformers: filename=sentence_transformers-2.0.0-cp37-none-any.whl size=126711 sha256=2a2fec1055387ba822f59d9a1fedefead2df7a514b8c52510665d5019683e4e4
  Stored in directory: /root/.cache/pip/wheels/38/d2/98/d191289a877a34c68aa67e05179521e060f96394a3e9336be6
Successfully built sentence-transformers
ERROR: transformers 4.8.2 has requirement huggingface-hub==0.0.12, but you'll have huggingface-hub 0.0.13 which is incompatible.


In [14]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('paraphrase-MiniLM-L6-v2')

### Testando a função SentenceTransformer com um exemplo

In [15]:
# Descarta espaços em branco à direita e à esquerda
exemplo=[data.iloc[800,1].strip()]  # a variável "exemplo" é uma lista
exemplo

['check-disks: eadmin1: 2005/12/08 10:37:26, Fault Status assert (Drive Array,Slot/Connector Number: 1)']

In [16]:
sentence_embeddings = model.encode(exemplo)

In [17]:
for sentence, embedding in zip(exemplo, sentence_embeddings):
    print("Sentence:", sentence)
    print("Embedding:", embedding)
    print("")

Sentence: check-disks: eadmin1: 2005/12/08 10:37:26, Fault Status assert (Drive Array,Slot/Connector Number: 1)
Embedding: [ 0.057674   -0.13608822  0.11382212 -0.20477492 -0.12267179 -0.28865188
  0.14422996  0.21675062 -0.12922424  0.06364021  0.04972259 -0.11027004
  0.02408817 -0.19720441 -0.68273425 -0.23621911 -0.08001402 -0.5565563
  0.5773699   0.20462348 -0.16361442 -0.09057283 -0.16092774  0.02124377
  0.16062507  0.03422112  0.6448717   0.54983044 -0.24165477 -0.2326906
  0.18685338  0.339476   -0.17761618  0.26042643 -0.26237467 -0.35388386
  0.07408612 -0.40928948 -0.25127313 -0.2722578   0.1919492  -0.21604978
  0.06042353  0.21664153  0.17221147  0.410551    0.16144252  0.16191483
  0.01811063 -0.18300556  0.33762708  0.29225948  0.38180983 -0.00701549
  0.11001487 -0.11251036  0.3354684   0.01514309  0.18956028  0.463561
  0.5194152  -0.48251975  0.14126399 -0.30664217 -0.12365806  0.24114603
  0.34752834 -0.12565121 -0.115036    0.1619677   0.04447768  0.1689546
 -0.12

In [18]:
type(embedding)

numpy.ndarray

In [19]:
embedding.shape

(384,)

In [20]:
type(sentence_embeddings)

numpy.ndarray

In [21]:
sentence_embeddings

array([[ 0.057674  , -0.13608822,  0.11382212, -0.20477492, -0.12267179,
        -0.28865188,  0.14422996,  0.21675062, -0.12922424,  0.06364021,
         0.04972259, -0.11027004,  0.02408817, -0.19720441, -0.68273425,
        -0.23621911, -0.08001402, -0.5565563 ,  0.5773699 ,  0.20462348,
        -0.16361442, -0.09057283, -0.16092774,  0.02124377,  0.16062507,
         0.03422112,  0.6448717 ,  0.54983044, -0.24165477, -0.2326906 ,
         0.18685338,  0.339476  , -0.17761618,  0.26042643, -0.26237467,
        -0.35388386,  0.07408612, -0.40928948, -0.25127313, -0.2722578 ,
         0.1919492 , -0.21604978,  0.06042353,  0.21664153,  0.17221147,
         0.410551  ,  0.16144252,  0.16191483,  0.01811063, -0.18300556,
         0.33762708,  0.29225948,  0.38180983, -0.00701549,  0.11001487,
        -0.11251036,  0.3354684 ,  0.01514309,  0.18956028,  0.463561  ,
         0.5194152 , -0.48251975,  0.14126399, -0.30664217, -0.12365806,
         0.24114603,  0.34752834, -0.12565121, -0.1

#Estrutura da dados para alimentar a rede neural
Coluna 1: anomalia ou não

Coluna 2: embedding da frase da mensagem de erro

In [22]:
data

class                                               text
0        1  kernel: [KERNEL_IB][tsIbTavorMadProcess][/mnt_...
1        1  kernel: [KERNEL_IB][tsIbTavorMadProcess][/mnt_...
2        1  kernel: [KERNEL_IB][tsIbTavorMadProcess][/mnt_...
3        1  kernel: [KERNEL_IB][tsIbTavorMadProcess][/mnt_...
4        1  kernel: [KERNEL_IB][tsIbTavorMadProcess][/mnt_...
...    ...                                                ...
2008     0  kernel: e1000: eth0: e1000_watchdog: NIC Link ...
2009     0  kernel: e1000: eth1: e1000_probe: Intel(R) PRO...
2010     0  kernel: ehci_hcd 0000:00:1d.7: EHCI Host Contr...
2011     0  kernel: ehci_hcd 0000:00:1d.7: USB 2.0 enabled...
2012     0  kernel: ehci_hcd 0000:00:1d.7: irq 193, pci me...

[2013 rows x 2 columns]

In [23]:
# Gerando numpy array com os embeddings de cada linha
import numpy
numpy.array(model.encode(data['text']))

array([[-0.31695512, -0.2445666 , -0.15453957, ...,  0.0537153 ,
        -0.09574302, -0.04190569],
       [-0.31695512, -0.2445666 , -0.15453957, ...,  0.0537153 ,
        -0.09574302, -0.04190569],
       [-0.31695512, -0.2445666 , -0.15453957, ...,  0.0537153 ,
        -0.09574302, -0.04190569],
       ...,
       [-0.07210371,  0.07966992, -0.15915278, ...,  0.2900684 ,
         0.02040476,  0.3435507 ],
       [ 0.10172076,  0.08392867,  0.15593071, ...,  0.12103582,
         0.3310442 ,  0.35368806],
       [-0.22535361, -0.0545542 , -0.17760642, ..., -0.03752958,
         0.22706683,  0.05565814]], dtype=float32)

-----------------------------------------

In [24]:
transformado=numpy.array(model.encode(data['text']))

In [25]:
transformado.shape

(2013, 384)

## Separar base em treino e teste

In [26]:
data.describe()

class                                               text
count   2013                                               2013
unique     2                                                963
top        1  kernel: [KERNEL_IB][tsIbTavorMadProcess][/mnt_...
freq    1013                                                200

In [27]:
data.shape

(2013, 2)

In [28]:
nlinhas = data.shape[0]
nlinhas

2013

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
X_train, X_test, y_train, y_test = train_test_split(transformado,data['class'],test_size=0.2)

In [31]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1610, 384)
(403, 384)
(1610,)
(403,)


#Montando a Rede Neural

In [32]:
#Utilizar uma versão do tensorflow anterior a 2.0
%tensorflow_version 1.x

TensorFlow is already loaded. Please restart the runtime to change versions.


In [33]:
#NumberOfClasses = len(y_train.unique())
NumberOfClasses = len(data['class'].unique())

from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
y_train = labelencoder_y.fit_transform(y_train)
y_test = labelencoder_y.fit_transform(y_test)
print(y_train)

[1 0 1 ... 0 1 1]


## Criação  e dimensionamento

In [34]:
from keras import Sequential
from keras.layers import Dense
from keras.optimizers import SGD

In [35]:
X_train.shape[1:]

(384,)

In [36]:
RN = Sequential()
# activation = sigmoid / relu / 
RN.add(Dense(384, input_shape = X_train.shape[1:], activation = 'relu'))
RN.add(Dense(256,activation = 'relu'))
# Função de ativação obrigatoriamente sigmóide pelo fato da saída ser binária
RN.add(Dense(NumberOfClasses/2,activation = 'sigmoid'))

RN.summary()


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 384)               147840    
_________________________________________________________________
dense_1 (Dense)              (None, 256)               98560     
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 257       
Total params: 246,657
Trainable params: 246,657
Non-trainable params: 0
_________________________________________________________________


In [37]:
# treinamento
##from keras.utils import to_categorical
np.random.seed(0)
#### ? tf.set_random_seed=0
#optimizer: adam/sgd
#RN.compile(optimizer = 'adam', loss = 'mean_squared_error', metrics = ['accuracy']) 
RN.compile(optimizer = 'sgd', loss = 'binary_crossentropy', metrics = ['accuracy']) 
trainedRN = RN.fit(X_train,y_train, epochs = 200, verbose = 1)


Epoch 1/200
51/51 [==============================] - 14s 2ms/step - loss: 0.6200 - accuracy: 0.7788
Epoch 2/200
51/51 [==============================] - 0s 2ms/step - loss: 0.4648 - accuracy: 0.8675
Epoch 3/200
51/51 [==============================] - 0s 2ms/step - loss: 0.3542 - accuracy: 0.9042
Epoch 4/200
51/51 [==============================] - 0s 2ms/step - loss: 0.2640 - accuracy: 0.9473
Epoch 5/200
51/51 [==============================] - 0s 2ms/step - loss: 0.2073 - accuracy: 0.9592
Epoch 6/200
51/51 [==============================] - 0s 2ms/step - loss: 0.1634 - accuracy: 0.9749
Epoch 7/200
51/51 [==============================] - 0s 2ms/step - loss: 0.1266 - accuracy: 0.9846
Epoch 8/200
51/51 [==============================] - 0s 2ms/step - loss: 0.1051 - accuracy: 0.9867
Epoch 9/200
51/51 [==============================] - 0s 2ms/step - loss: 0.0829 - accuracy: 0.9887
Epoch 10/200
51/51 [==============================] - 0s 2ms/step - loss: 0.0742 - accuracy: 0.9878
Epoch 11

## Avaliação da rede neural

In [38]:
# avaliação
score = trainedRN.model.evaluate(X_test, y_test, verbose = 1)
print('Test score:', score[0])
print('Test mape:', score[1], '%')

13/13 [==============================] - 0s 2ms/step - loss: 0.0094 - accuracy: 0.9950
Test score: 0.009430119767785072
Test mape: 0.9950371980667114 %


Confirmando as classes na base de teste ('0' ou '1')

In [39]:
Qtd_Total= y_test.shape
Qtd_Classe_1=y_test.sum()
Qtd_Classe_0 = Qtd_Total - Qtd_Classe_1

In [40]:
print ("Quantidade relativa na classe 0: " , Qtd_Classe_0 / Qtd_Total)
print ("Quantidade relativa na classe 1: " , Qtd_Classe_1 / Qtd_Total)

Quantidade relativa na classe 0:  [0.48138958]
Quantidade relativa na classe 1:  [0.51861042]


#Resultados

ERRADO

92%

*   RN.add(Dense(384, input_shape = X_train.shape[1:], activation = 'relu'))
*   RN.add(Dense(256,activation = 'relu'))
*   RN.add(Dense(NumberOfClasses,activation = 'relu'))
*   RN.compile(optimizer = 'sgd', loss = 'mean_squared_error', metrics = ['accuracy'])
*   trainedRN = RN.fit(X_train,y_train, epochs = 200, verbose = 1)

99%
RN.add(Dense(384, input_shape = X_train.shape[1:], activation = 'relu'))
RN.add(Dense(256,activation = 'relu'))
RN.add(Dense(NumberOfClasses,activation = 'relu'))
RN.summary()
np.random.seed(0)
tf.set_random_seed=0
RN.compile(optimizer = 'adam', loss = 'mean_squared_error', metrics = ['accuracy']) 
trainedRN = RN.fit(X_train,y_train, epochs = 200, verbose = 1)

In [41]:
X_train

array([[-0.31695512, -0.2445666 , -0.15453957, ...,  0.0537153 ,
        -0.09574302, -0.04190569],
       [-0.06627509, -0.09221895, -0.04679343, ...,  0.37466004,
        -0.19903943, -0.05389589],
       [-0.18138225,  0.07175694, -0.6481264 , ...,  0.14847657,
        -0.22849394,  0.26751047],
       ...,
       [-0.16507034, -0.15256251, -0.34344548, ...,  0.08420863,
         0.16021141, -0.17284565],
       [-0.31071877, -0.09669941,  0.2725609 , ..., -0.30560365,
        -0.4754275 ,  0.21095714],
       [ 0.04474398, -0.10664073, -0.12951486, ...,  0.16739833,
        -0.02182664,  0.23816536]], dtype=float32)

In [42]:
y_test

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,

In [43]:
y_train

array([1, 0, 1, ..., 0, 1, 1])

Salvando o modelo final da rede neural, com os pesos

model.save_weights('arquivo') / model.load_weights('arquivo')

In [45]:
RN.save("Rede neural salva")

INFO:tensorflow:Assets written to: Rede neural salva/assets


In [44]:
# Aplicando o modelo
mensagem="attempting task abort"
model.encode(mensagem)
## valia=RN.predict(model.encode(mensagem),batch_size=384,verbose=2 )[1]

array([ 2.51232117e-01,  1.15778506e-01, -3.94952111e-02, -1.25418201e-01,
        9.59883407e-02, -6.34235740e-02,  4.94778425e-01,  3.79047245e-01,
        6.02467209e-02,  1.60277307e-01, -2.44485810e-01,  1.72003075e-01,
       -3.68332893e-01, -1.31171932e-02, -2.98640102e-01, -6.44647852e-02,
        3.27891707e-01, -1.94101974e-01, -2.95335561e-01,  3.20579380e-01,
       -2.36499369e-01, -2.76249796e-02, -3.37112755e-01,  4.81980652e-01,
       -3.87514126e-03,  3.02870661e-01, -3.40172678e-01,  3.70573312e-01,
       -2.00924590e-01,  3.20709683e-02,  1.00117780e-01, -4.86959457e-01,
       -3.92596833e-02, -4.58563328e-01,  6.85253143e-01,  6.65273294e-02,
       -7.46057093e-01, -3.08502674e-01,  9.67414007e-02, -6.20163083e-01,
       -7.64006898e-02,  1.67352453e-01, -5.66029489e-01,  3.05522084e-01,
       -1.22478895e-01,  4.16288108e-01, -7.19080150e-01,  1.32273987e-01,
        1.30554855e-01,  2.01190308e-01, -8.99751186e-01,  3.87498885e-01,
        3.33523661e-01, -